# Generated by Django 5.2 on 2025-05-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_description_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='https://chustfeelfoodbackend.onrender.com/api/products/'),
        ),
    ]
