# Generated by Django 5.2 on 2025-05-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Ovqatlar'), ('drink', 'Ichimliklar'), ('cake', 'Tortlar')], default='food', help_text='Kategoriya: ovqatlar, ichimliklar yoki tortlar', max_length=10),
        ),
    ]
