# Generated by Django 5.2 on 2025-05-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', '🍔 Taomlar'), ('drink', '🥤 Ichimliklar'), ('cake', '🍰 Desertlar')], default='food', help_text='Kategoriya: ovqatlar, ichimliklar yoki tortlar', max_length=10),
        ),
    ]
